// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function equals(a, b) {
  return Math.abs(a - b) < 0.0001;
}

var epsilon = 0.0001;

exports.epsilon = epsilon;
exports.equals = equals;
/* No side effect */
