// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var fullCircle = 2 * Math.PI;

var halfCircle = Math.PI;

var quarterCircle = Math.PI / 2;

function fromDegrees(deg) {
  return deg / 180 * Math.PI;
}

exports.fullCircle = fullCircle;
exports.halfCircle = halfCircle;
exports.quarterCircle = quarterCircle;
exports.fromDegrees = fromDegrees;
/* fullCircle Not a pure module */
